### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by 3ffusi0on** [inket/RubyXDCCGetter#1]
While running your project, there are multiple warnings, all caused by the same "error"

> ./RubyXDCCGetter/xdcc.rb:71: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:72: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:73: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:74: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:75: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:76: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:82: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:84: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:86: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:97: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:113: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:114: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:115: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:116: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:116: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:117: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:118: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:129: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:130: warning: class variable access from toplevel
> ./RubyXDCCGetter/xdcc.rb:130: warning: class variable access from toplevel
> Starting bot...
> Connecting...
> Connected.

Regards,

**Comment by jopek** [comment]
@3ffusi0on run with ruby **-W0** xdcc.rb <server> <bot_name> <file_number> [-c <channel_name>] [-d <download_folder>] [-o <bot_log_file>]
